apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: turnbulls
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: turnbulls
    spec:
      containers:
        - name: turnbulls
          image: docker.io/jsakon/hackathon
          ports:
            - containerPort: 8080